name       : haskell-integer-logarithms
version    : 1.0.2.1
release    : 1
source     :
    - https://hackage.haskell.org/package/integer-logarithms-1.0.2.1/integer-logarithms-1.0.2.1.tar.gz : 32ad4a482a60ec957d1af1268952e2a6b382b67438c14f74f6c2aef2e49b48f2
license    : MIT
component  : programming.haskell
summary    : Math.NumberTheory.Logarithms splitted out of arithmoi
description: |
    Math.NumberTheory.Logarithms splitted out of arithmoi
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
