name       : haskell-integer-logarithms
version    : 1.0.3
release    : 2
source     :
    - https://hackage.haskell.org/package/integer-logarithms-1.0.3/integer-logarithms-1.0.3.tar.gz : 5ae262018698af35bb74916fad170d96d3eb44669c72ed36db9a19a3392cec16
license    : MIT
component  : programming.haskell
summary    : Math.NumberTheory.Logarithms splitted out of arithmoi
description: |
    Math.NumberTheory.Logarithms splitted out of arithmoi
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
